const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({headless: true, channel: 'msedge'});
  const context = await browser.newContext({viewport:{width:1280,height:900}});
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const out = path.resolve('test-results');
  fs.mkdirSync(out,{recursive:true});
  let passed = 0;
  const check = (value, label) => { assert.ok(value,label); passed++; console.log('PASS '+label); };
  try {
    await page.goto('http://127.0.0.1:8001/');
    await page.locator('.card').first().waitFor();
    check(await page.locator('.card').count()===12,'REST-01 initial page size');
    await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});
    await page.locator('#next').click();
    await page.getByText('第 2 頁',{exact:true}).waitFor();
    check(await page.locator('.card').count()===3,'REST-01 next page');
    await page.reload();
    await page.getByText('第 2 頁',{exact:true}).waitFor();
    check(new URL(page.url()).searchParams.get('page')==='2','pagination refresh');
    await page.locator('#query').fill('特殊');
    await page.locator('#search-form button').click();
    await page.getByRole('heading',{name:'<b>特殊 & 餐廳</b>',exact:true}).waitFor();
    check(await page.locator('#restaurants b').count()===0,'REST-04 name rendered as text');
    await page.locator('.card').click();
    await page.locator('#detail-title').filter({hasText:'<b>特殊 & 餐廳</b>'}).waitFor();
    check(await page.locator('#detail-body a').count()===0,'unsafe website not clickable');
    check((await page.locator('#detail-body').innerText()).includes('營業時間未提供'),'REST-03 missing hours');
    await page.reload();
    await page.locator('#detail-title').filter({hasText:'<b>特殊 & 餐廳</b>'}).waitFor();
    check(await page.locator('#detail').isVisible(),'detail refresh');
    await page.keyboard.press('Escape');
    check(!(await page.locator('#detail').isVisible()),'keyboard close');
    await page.locator('#query').fill('街角');
    await page.locator('#search-form button').click();
    await page.getByRole('heading',{name:'街角小食堂',exact:true}).waitFor();
    await page.locator('.card').click();
    await page.getByText('<b>評論文字</b> & 好吃',{exact:true}).waitFor();
    check(await page.locator('#reviews b').count()===0,'REST-04 review text not HTML');
    check((await page.locator('#detail-body').innerText()).includes('原始評分與發布時間未提供'),'REST-06 missing date and rating disclosure');
    await page.locator('#close-detail').click();
    await page.locator('#query').fill('完全不存在的餐廳');
    await page.locator('#search-form button').click();
    await page.getByText('沒有符合條件的餐廳。試試其他店名、地址或分類。').waitFor();
    check(await page.locator('.card').count()===0,'REST-05 empty clears stale cards');
    await page.screenshot({path:path.join(out,'empty.png')});
    await page.route('**/api/v1/restaurants?**', route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'資料庫暫時無法使用，請稍後重試'}})}));
    await page.locator('#query').fill('');
    await page.locator('#search-form button').click();
    await page.locator('#retry').waitFor();
    check((await page.locator('#list-status').innerText()).includes('資料庫暫時無法使用'),'REST-05 server error distinguished');
    await page.screenshot({path:path.join(out,'error.png')});
    await page.unroute('**/api/v1/restaurants?**');
    await page.locator('#retry').click();
    await page.locator('.card').first().waitFor();
    check(await page.locator('.card').count()===12,'retry recovers');
    await context.setOffline(true);
    await page.locator('#search-form button').click();
    await page.locator('#retry').waitFor();
    check((await page.locator('#list-status').innerText()).includes('無法連線'),'REST-05 offline state');
    await context.setOffline(false);
    await page.locator('#retry').click();
    await page.locator('.card').first().waitFor();
    await page.setViewportSize({width:390,height:844});
    check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'390px no horizontal overflow');
    await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
    await page.locator('.card').first().click();
    await page.locator('#detail-title').filter({hasText:'街角小食堂'}).waitFor();
    await page.getByText('<b>評論文字</b> & 好吃',{exact:true}).waitFor();
    check(await page.locator('#close-detail').isVisible(),'mobile detail close visible');
    await page.screenshot({path:path.join(out,'mobile-detail.png')});
    check(errors.length===0,'no browser JavaScript errors');
    console.log(passed+' browser assertions passed. '+await browser.version());
    fs.writeFileSync(path.join(out,'browser-result.json'),JSON.stringify({passed,version:await browser.version(),viewport:[1280,900,390,844],errors},null,2));
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
