const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const BASE='http://127.0.0.1:8004',EMAIL=process.env.V2_BROWSER_EMAIL,FRIEND_EMAIL=process.env.V2_BROWSER_FRIEND_EMAIL;
if(!EMAIL||!process.env.V2_BROWSER_MAILBOX)throw Error('Use guarded Python launcher');
const checks=[];const pass=x=>{checks.push(x);console.log('PASS '+x)};
const otp=purpose=>JSON.parse(fs.readFileSync(process.env.V2_BROWSER_MAILBOX,'utf8')).filter(x=>x.email===EMAIL&&x.purpose===purpose).at(-1).code;
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,serviceWorkers:'block'});
 await context.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
 const page=await context.newPage(),errors=[];
 page.on('pageerror',e=>{errors.push(e.message);console.error('PAGEERROR',e.message)});page.on('dialog',d=>{console.log('DIALOG',d.message());d.accept();});page.on('response',async r=>{if(r.url().includes('/api/')&&r.status()>=400)console.error('API status',r.status(),new URL(r.url()).pathname)});
 try{
 await page.goto(BASE+'/signup.html');
 await page.fill('#nameInput','<b>Browser User</b>');await page.locator('#dobInput').focus();await page.fill('#dobInput','2000-01-01');
 await page.fill('#accountInput','browser_user');await page.fill('#emailInput',EMAIL);await page.fill('#phoneInput','0912345678');await page.fill('#passwordInput','Browser-password-1');
 await page.click('#signupBtn');await page.waitForURL('**/otp_verify.html?**');
 await page.fill('#real-input',otp('signup'));await page.click('#verifyBtn');await page.waitForURL('**/onboarding.html');
 pass('原註冊表單 → OTP → 六題偏好');
 for(let i=0;i<6;i++){await page.click('#optionLeft');await page.click('#nextBtn');}
 await page.waitForURL('**/index.html?tab=home');
 const me=await (await context.request.get(BASE+'/api/me')).json();assert.equal(Object.keys(me.preferences.answers).length,6);assert.equal(me.username,'browser_user');pass('六題偏好與帳號已保存 PostgreSQL');
 await context.request.post(BASE+'/api/logout');await page.goto(BASE+'/login.html');await page.fill('#emailInput','browser_user');await page.fill('#passwordInput','Browser-password-1');await page.click('#loginBtn');await page.waitForURL('**/index.html');const accountLoginCheck=await page.evaluate(async()=>({username:localStorage.getItem('myProfileUsername'),status:(await fetch('/api/me')).status}));assert.equal(accountLoginCheck.username,'browser_user');assert.equal(accountLoginCheck.status,200);pass('登入頁接受使用者帳號');
 await page.goto(BASE+'/profile.html');await page.waitForFunction(()=>document.querySelector('#handle-field')?.textContent.trim()==='browser_user',{timeout:10000});await page.locator('#handle-field').fill('browser.ui_account');await page.locator('#handle-field').press('Tab');await page.waitForFunction(()=>localStorage.getItem('myProfileUsername')==='browser.ui_account');assert.equal((await (await context.request.get(BASE+'/api/me')).json()).username,'browser.ui_account');pass('個人頁修改帳號並保存至 PostgreSQL');
 await page.goto(BASE+'/friends.html');await page.fill('#friendSearch','browser_friend');await page.click('#searchBtn');await page.locator('#searchResults [data-user-id]').waitFor();await page.locator('#searchResults [data-user-id]').click();await page.waitForFunction(()=>document.querySelector('#searchResults [data-user-id]')?.textContent.includes('已送出'));pass('好友頁搜尋帳號並送出請求');
 await context.request.post(BASE+'/api/logout');await context.request.post(BASE+'/api/login',{data:{email:FRIEND_EMAIL,password:'Friend-password-1'}});await page.goto(BASE+'/message.html');await page.locator('#friendRequestNotifications [data-action=approve]').waitFor();await page.locator('#friendRequestNotifications [data-action=approve]').click();await page.waitForFunction(()=>!document.querySelector('#friendRequestNotifications [data-action=approve]'));pass('最新消息批准好友請求');
 await context.request.post(BASE+'/api/logout');await context.request.post(BASE+'/api/login',{data:{email:EMAIL,password:'Browser-password-1'}});await page.goto(BASE+'/friends.html');await page.locator('#friendList').getByText('Browser Friend').waitFor();pass('好友列表顯示已建立關係');
 await page.locator('#friendList [data-chat-id]').click();await page.waitForURL('**/chat.html?friend_id=*');await page.fill('#messageInput','嗨，這是聊天室測試');await page.click('#sendButton');await page.waitForFunction(()=>document.querySelector('#messages').textContent.includes('嗨，這是聊天室測試'));pass('好友列表點擊好友進入聊天室並送出訊息');
 await context.request.post(BASE+'/api/logout');await context.request.post(BASE+'/api/login',{data:{email:FRIEND_EMAIL,password:'Friend-password-1'}});await page.goto(BASE+'/chat.html?friend_id='+me.id);await page.waitForFunction(()=>document.querySelector('#messages').textContent.includes('嗨，這是聊天室測試'));pass('另一個帳號讀取好友聊天室訊息');
 await context.request.post(BASE+'/api/logout');await context.request.post(BASE+'/api/login',{data:{email:EMAIL,password:'Browser-password-1'}});
 await page.goto(BASE+'/edit.html');await page.setInputFiles('#imageLoader',[path.resolve('frontend/IMG_1940.jpg'),path.resolve('frontend/IMG_3535.jpg')]);
 await page.click('#locationBtn');await page.getByRole('textbox',{name:'搜尋',exact:true}).fill('Browser');
 await page.locator('.picker-list button').filter({hasText:'Browser Restaurant'}).click();await page.locator('dialog [data-action=apply]').click();
 await page.click('#tagFriendBtn');await page.getByRole('textbox',{name:'搜尋',exact:true}).fill('Browser Friend');
 await page.locator('.picker-list button').filter({hasText:'Browser Friend'}).click();await page.locator('dialog [data-action=apply]').click();
 await page.click('#shareBtn');await page.waitForURL('**/index.html');
 let posts=await (await context.request.get(BASE+'/api/get_memories')).json();assert.equal(posts.length,1);let post=posts[0];
 assert.equal(post.imageUrls.length,2);assert.equal(post.location,'Browser Restaurant');assert.equal(post.mentions.length,1);pass('原 Finish 保存兩張照片、餐廳與好友標註');
 await page.evaluate(()=>goToPage(0,false));const memoriesFrame=page.frames().find(f=>f.url().includes('/memories.html'));assert.ok(memoriesFrame,'memories frame should be mounted');await memoriesFrame.locator('#monthlyRecapHost .monthly-recap-card').waitFor({timeout:15000});assert.match(await memoriesFrame.locator('#monthlyRecapHost').innerText(),/MONTHLY RECAP/);await memoriesFrame.locator('[data-monthly-recap]').click();
 const recapFrame=page.locator('#featureFrame').contentFrame();await recapFrame.locator('.hero').waitFor({timeout:15000});assert.equal(await recapFrame.locator('.timeline-item').count(),1);assert.equal(await recapFrame.locator('.insight-grid .insight').count(),4);await recapFrame.locator('#noteInput').fill('給未來的自己：繼續記得一起吃飯。');await recapFrame.locator('[data-save=note]').click();assert.equal(await recapFrame.locator('#noteInput').inputValue(),'給未來的自己：繼續記得一起吃飯。');pass('月回顧封面、統計、時間軸與個人筆記');await recapFrame.locator('#backButton').click();await page.waitForFunction(()=>document.querySelector('#featureOverlay')?.style.display==='none'&&location.pathname.endsWith('/index.html'),{timeout:10000});pass('月回顧返回 My Memories');
 await page.locator('#swipeWrapper').waitFor({state:'visible',timeout:15000});await page.evaluate(()=>goToPage(2,false));
 const socialFrame=page.frames().find(f=>f.url().includes('/social.html'));assert.ok(socialFrame,'social frame should be mounted');await socialFrame.locator('#mineFeed article.post-card').first().waitFor();
 await page.evaluate(()=>{window.__featureTrace=[];window.__featureTraceTimer=setInterval(()=>{const overlay=document.querySelector('#featureOverlay');const frame=document.querySelector('#featureFrame');const body=frame?.contentDocument?.body;window.__featureTrace.push({overlayVisible:overlay?.style.display==='block'&&getComputedStyle(overlay).visibility==='visible',bodyVisible:body?.style.visibility!=='hidden',panelReady:body?.classList.contains('comments-sheet-ready')});},2);});
 await socialFrame.evaluate(id=>window.openComments(id,'mine'),post.id);await page.waitForFunction(()=>{const frame=document.querySelector('#featureFrame');return document.querySelector('#featureOverlay')?.style.display==='block'&&frame?.contentDocument?.body?.classList.contains('comments-sheet-ready')},{timeout:15000});
 const featureTrace=await page.evaluate(()=>{clearInterval(window.__featureTraceTimer);return window.__featureTrace||[];});assert.ok(featureTrace.length>0);assert.equal(featureTrace.filter(item=>item.overlayVisible&&!item.panelReady).length,0,'comment overlay must wait for ready panel');assert.equal(await page.locator('#featureFrame').evaluate(frame=>frame.contentDocument?.querySelectorAll('.comments-sheet-panel').length),1);pass('留言面板先完成初始化再顯示，避免整頁閃爍');
 const commentsFrame=page.locator('#featureFrame').contentFrame();await commentsFrame.locator('.back-btn').waitFor({timeout:10000});await commentsFrame.locator('.back-btn').click();await page.waitForFunction(()=>document.querySelector('#featureOverlay')?.style.display==='none'&&location.pathname.endsWith('/index.html'),{timeout:10000});pass('留言頁返回主框架並恢復左右切換');
 for(let i=0;i<6;i++){await socialFrame.evaluate(id=>window.openComments(id,'mine'),post.id);await page.waitForFunction(()=>document.querySelector('#featureOverlay')?.style.display==='block',{timeout:5000});await page.evaluate(()=>closeFeaturePage());await page.waitForFunction(()=>document.querySelector('#featureOverlay')?.style.display==='none'&&location.pathname.endsWith('/index.html'),{timeout:10000});}
 await socialFrame.evaluate(id=>window.openComments(id,'mine'),post.id);await page.waitForFunction(()=>{const frame=document.querySelector('#featureFrame');return document.querySelector('#featureOverlay')?.style.display==='block'&&frame?.contentDocument?.body?.classList.contains('comments-sheet-ready')},{timeout:15000});assert.equal(await page.locator('#featureFrame').evaluate(frame=>frame.contentDocument?.querySelectorAll('.comments-sheet-panel').length),1);pass('留言頁快速開關 6 次後仍可正常顯示且無殘留面板');
 const finalCommentsFrame=page.locator('#featureFrame').contentFrame();await finalCommentsFrame.locator('.back-btn').waitFor({timeout:10000});await finalCommentsFrame.locator('.back-btn').click();await page.waitForFunction(()=>document.querySelector('#featureOverlay')?.style.display==='none'&&location.pathname.endsWith('/index.html'),{timeout:10000});
 await page.goto(BASE+'/edit.html?id='+post.id+'&from=social');await page.waitForFunction(()=>document.querySelector('#locationBtn').textContent.includes('Browser Restaurant'));
 assert.match(await page.locator('#tagFriendBtn').getAttribute('title'),/Browser Friend/);pass('重新編輯還原地點及好友');
 await page.goto(BASE+'/comments.html?id='+post.id);await page.fill('#input-box','<img src=x onerror=alert(1)>');await page.click('#post-btn');
 await page.waitForFunction(()=>document.querySelector('#comments-list').textContent.includes('<img src=x'));
 assert.equal(await page.locator('#comments-list img[src=x]').count(),0);pass('留言保存且文字不執行 HTML');
 await page.goto(BASE+'/payment.html');assert.equal(await page.locator('input:not([readonly])').count(),0);
 await page.click('#payBtn');await page.waitForFunction(()=>localStorage.getItem('isPremiumUser')==='true');
 assert.equal((await (await context.request.get(BASE+'/api/me')).json()).is_premium,true);pass('Demo 付款不收卡號並保存示意會員');
 await page.goto(BASE+'/social.html');await page.waitForSelector('#mineFeed article.post-card');assert.equal(await page.locator('.username b').count(),0);
 const mentionToggle=page.locator('#mineFeed .mention-toggle').first();await mentionToggle.waitFor();assert.equal(await mentionToggle.isVisible(),true);
 await mentionToggle.click();const mentionPopover=page.locator('#mineFeed .mention-popover').first();assert.equal(await mentionPopover.getAttribute('aria-hidden'),'false');assert.match(await mentionPopover.innerText(),/Browser Friend/);
 await mentionToggle.click();assert.equal(await mentionPopover.getAttribute('aria-hidden'),'true');await mentionToggle.click();await page.evaluate(()=>document.body.dispatchEvent(new MouseEvent('click',{bubbles:true})));assert.equal(await mentionPopover.getAttribute('aria-hidden'),'true');pass('社群貼文圖片顯示標記好友按鈕與動畫彈窗');
 await context.request.post(BASE+'/api/logout');await context.request.post(BASE+'/api/login',{data:{email:FRIEND_EMAIL,password:'Friend-password-1'}});
 await page.goto(BASE+'/social.html');await page.locator('#mineFeed article.post-card').first().waitFor();
 assert.equal(await page.locator('.mine-filter-btn').count(),3);assert.equal(await page.locator('.post-context.tagged').count(),1);
 await page.locator('.mine-filter-btn[data-filter=tagged]').click();await page.waitForFunction(()=>document.querySelectorAll('#mineFeed article.post-card').length===1);
 await page.locator('.mine-filter-btn[data-filter=mine]').click();await page.waitForFunction(()=>document.querySelectorAll('#mineFeed article.post-card').length===0);
 await page.locator('.mine-filter-btn[data-filter=all]').click();await page.waitForFunction(()=>document.querySelectorAll('#mineFeed article.post-card').length===1);pass('我的社群顯示狀態標籤與三種貼文篩選');
 await page.locator('#mineFeed .more-btn').first().click();
 assert.equal(await page.locator('#menu-mine-'+post.id+' .menu-item').count(),2);assert.match(await page.locator('#menu-mine-'+post.id).innerText(),/取消被標記/);assert.match(await page.locator('#menu-mine-'+post.id).innerText(),/檢舉/);pass('被標記貼文僅提供取消標記與檢舉');
 await page.locator('#menu-mine-'+post.id+' .menu-item').filter({hasText:'檢舉'}).click();
 await page.goto(BASE+'/memories.html');await page.locator('.day-cell img').first().waitFor();await page.locator('.day-cell img').first().click();await page.waitForSelector('#storyOverlay.active');
 await page.locator('#storyMenuButton').waitFor({state:'visible'});await page.click('#storyMenuButton');assert.equal(await page.locator('#storyMenu').getAttribute('aria-hidden'),'false');assert.equal(await page.locator('#storyMenu [role=menuitem]').count(),2);
 await page.locator('#storyMenu [role=menuitem]').filter({hasText:'檢舉'}).click();await page.click('#storyMenuButton');await page.locator('#storyMenu [role=menuitem]').filter({hasText:'取消被標記'}).click();
 await page.waitForFunction(()=>!document.querySelector('#storyOverlay').classList.contains('active'));await page.waitForFunction(()=>document.querySelectorAll('.day-cell img').length===0);pass('被標記貼文進入 Memories，B 可檢舉或取消標記');
 await context.request.post(BASE+'/api/logout');await context.request.post(BASE+'/api/login',{data:{email:EMAIL,password:'Browser-password-1'}});await page.goto(BASE+'/social.html');await page.waitForSelector('#mineFeed article.post-card');
 await page.locator('#mineFeed .more-btn').first().click();await page.locator('.menu-item.delete').first().click();
 await page.waitForFunction(()=>document.querySelectorAll('#mineFeed .post-card').length===0);
 assert.equal((await (await context.request.get(BASE+'/api/get_memories')).json()).length,0);pass('社群刪除整則多圖紀錄');
 await page.goto(BASE+'/home.html');await page.click('.shutter-btn');assert.match(await page.locator('#action-sheet-overlay').getAttribute('class'),/show/);
 const quickResponse=page.waitForResponse(r=>r.url().endsWith('/api/upload_memory_post'));
 await page.setInputFiles('#input_gallery',path.resolve('frontend/IMG_1940.jpg'));
 const quick=await quickResponse;assert.equal(quick.status(),200,await quick.text());
 await page.waitForFunction(()=>document.querySelector('#displayImg').getAttribute('src').startsWith('/api/photos/'));
 assert.ok(page.url().endsWith('/home.html'));pass('快門相簿直接上傳並留在首頁');
 await page.goto(BASE+'/memories.html');await page.locator('.day-cell img').first().click();await page.waitForSelector('#storyOverlay.active');
 await page.click('#storyOverlay .delete-btn');await page.waitForFunction(()=>!document.querySelector('#storyOverlay').classList.contains('active'));
 await page.reload();assert.equal(await page.locator('.day-cell img').count(),0);pass('日曆限動刪除最後一圖，重載無舊照片');
 await page.goto(BASE+'/login.html');await context.request.post(BASE+'/api/logout');await page.goto(BASE+'/forgot-password.html');await page.fill('#emailInput',EMAIL);await page.click('#submitBtn');await page.waitForURL('**/otp_verify.html?**');
 await page.fill('#real-input',otp('reset_password'));await page.click('#verifyBtn');await page.waitForURL('**/reset_password.html?**');
 await page.fill('#newPass','Changed-password-2');await page.fill('#confirmPass','Changed-password-2');await page.click('#submitBtn');await page.waitForURL('**/login.html**');
 await page.fill('#emailInput','browser.ui_account');await page.fill('#passwordInput','Changed-password-2');await page.click('#loginBtn');await page.waitForURL('**/index.html');pass('忘記密碼 → OTP → 重設 → 新密碼登入');
 assert.deepEqual(errors,[]);pass('瀏覽器無 JavaScript 例外');
 fs.mkdirSync('test-results',{recursive:true});fs.writeFileSync('test-results/features.json',JSON.stringify({checks},null,2));
 }catch(e){console.error('Browser errors:',errors);console.error('Page:',await page.locator('body').innerText());throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
