const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const BASE='http://127.0.0.1:8004',EMAIL=process.env.V2_BROWSER_EMAIL,FRIEND_EMAIL=process.env.V2_BROWSER_FRIEND_EMAIL;
if(!EMAIL||!process.env.V2_BROWSER_MAILBOX)throw Error('Use guarded Python launcher');
const checks=[];const pass=x=>{checks.push(x);console.log('PASS '+x)};
const otp=purpose=>JSON.parse(fs.readFileSync(process.env.V2_BROWSER_MAILBOX,'utf8')).filter(x=>x.email===EMAIL&&x.purpose===purpose).at(-1).code;
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,serviceWorkers:'block'});
 await context.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
 const page=await context.newPage(),errors=[];
 page.on('pageerror',e=>{errors.push(e.message);console.error('PAGEERROR',e.message)});page.on('dialog',d=>{console.log('DIALOG',d.message());d.accept();});page.on('response',async r=>{if(r.url().includes('/api/')&&r.status()>=400)console.error('API status',r.status(),new URL(r.url()).pathname)});
 try{
 await page.goto(BASE+'/signup.html');
 await page.fill('#nameInput','<b>Browser User</b>');await page.locator('#dobInput').focus();await page.fill('#dobInput','2000-01-01');
 await page.fill('#emailInput',EMAIL);await page.fill('#phoneInput','0912345678');await page.fill('#passwordInput','Browser-password-1');
 await page.click('#signupBtn');await page.waitForURL('**/otp_verify.html?**');
 await page.fill('#real-input',otp('signup'));await page.click('#verifyBtn');await page.waitForURL('**/onboarding.html');
 pass('原註冊表單 → OTP → 六題偏好');
 for(let i=0;i<6;i++){await page.click('#optionLeft');await page.click('#nextBtn');}
 await page.waitForURL('**/index.html?tab=home');
 const me=await (await context.request.get(BASE+'/api/me')).json();assert.equal(Object.keys(me.preferences.answers).length,6);pass('六題偏好已保存 PostgreSQL');
 await page.goto(BASE+'/friends.html');await page.fill('#friendSearch','Browser Friend');await page.click('#searchBtn');await page.locator('#searchResults [data-user-id]').waitFor();await page.locator('#searchResults [data-user-id]').click();await page.waitForFunction(()=>document.querySelector('#searchResults [data-user-id]')?.textContent.includes('已送出'));pass('好友頁搜尋帳號並送出請求');
 await context.request.post(BASE+'/api/logout');await context.request.post(BASE+'/api/login',{data:{email:FRIEND_EMAIL,password:'Friend-password-1'}});await page.goto(BASE+'/message.html');await page.locator('#friendRequestNotifications [data-action=approve]').waitFor();await page.locator('#friendRequestNotifications [data-action=approve]').click();await page.waitForFunction(()=>!document.querySelector('#friendRequestNotifications [data-action=approve]'));pass('最新消息批准好友請求');
 await context.request.post(BASE+'/api/logout');await context.request.post(BASE+'/api/login',{data:{email:EMAIL,password:'Browser-password-1'}});await page.goto(BASE+'/friends.html');await page.locator('#friendList').getByText('Browser Friend').waitFor();pass('好友列表顯示已建立關係');
 await page.locator('#friendList [data-chat-id]').click();await page.waitForURL('**/chat.html?friend_id=*');await page.fill('#messageInput','嗨，這是聊天室測試');await page.click('#sendButton');await page.waitForFunction(()=>document.querySelector('#messages').textContent.includes('嗨，這是聊天室測試'));pass('好友列表點擊好友進入聊天室並送出訊息');
 await context.request.post(BASE+'/api/logout');await context.request.post(BASE+'/api/login',{data:{email:FRIEND_EMAIL,password:'Friend-password-1'}});await page.goto(BASE+'/chat.html?friend_id='+me.id);await page.waitForFunction(()=>document.querySelector('#messages').textContent.includes('嗨，這是聊天室測試'));pass('另一個帳號讀取好友聊天室訊息');
 await context.request.post(BASE+'/api/logout');await context.request.post(BASE+'/api/login',{data:{email:EMAIL,password:'Browser-password-1'}});
 await page.goto(BASE+'/edit.html');await page.setInputFiles('#imageLoader',[path.resolve('frontend/IMG_1940.jpg'),path.resolve('frontend/IMG_3535.jpg')]);
 await page.click('#locationBtn');await page.getByRole('textbox',{name:'搜尋',exact:true}).fill('Browser');
 await page.locator('.picker-list button').filter({hasText:'Browser Restaurant'}).click();await page.locator('dialog [data-action=apply]').click();
 await page.click('#tagFriendBtn');await page.getByRole('textbox',{name:'搜尋',exact:true}).fill('Browser Friend');
 await page.locator('.picker-list button').filter({hasText:'Browser Friend'}).click();await page.locator('dialog [data-action=apply]').click();
 await page.click('#shareBtn');await page.waitForURL('**/index.html');
 let posts=await (await context.request.get(BASE+'/api/get_memories')).json();assert.equal(posts.length,1);let post=posts[0];
 assert.equal(post.imageUrls.length,2);assert.equal(post.location,'Browser Restaurant');assert.equal(post.mentions.length,1);pass('原 Finish 保存兩張照片、餐廳與好友標註');
 await page.goto(BASE+'/edit.html?id='+post.id+'&from=social');await page.waitForFunction(()=>document.querySelector('#locationBtn').textContent.includes('Browser Restaurant'));
 assert.match(await page.locator('#tagFriendBtn').getAttribute('title'),/Browser Friend/);pass('重新編輯還原地點及好友');
 await page.goto(BASE+'/comments.html?id='+post.id);await page.fill('#input-box','<img src=x onerror=alert(1)>');await page.click('#post-btn');
 await page.waitForFunction(()=>document.querySelector('#comments-list').textContent.includes('<img src=x'));
 assert.equal(await page.locator('#comments-list img[src=x]').count(),0);pass('留言保存且文字不執行 HTML');
 await page.goto(BASE+'/payment.html');assert.equal(await page.locator('input:not([readonly])').count(),0);
 await page.click('#payBtn');await page.waitForFunction(()=>localStorage.getItem('isPremiumUser')==='true');
 assert.equal((await (await context.request.get(BASE+'/api/me')).json()).is_premium,true);pass('Demo 付款不收卡號並保存示意會員');
 await page.goto(BASE+'/social.html');await page.waitForSelector('#mineFeed article.post-card');assert.equal(await page.locator('.username b').count(),0);
 const mentionToggle=page.locator('#mineFeed .mention-toggle').first();await mentionToggle.waitFor();assert.equal(await mentionToggle.isVisible(),true);
 await mentionToggle.click();const mentionPopover=page.locator('#mineFeed .mention-popover').first();assert.equal(await mentionPopover.getAttribute('aria-hidden'),'false');assert.match(await mentionPopover.innerText(),/Browser Friend/);
 await mentionToggle.click();assert.equal(await mentionPopover.getAttribute('aria-hidden'),'true');await mentionToggle.click();await page.evaluate(()=>document.body.dispatchEvent(new MouseEvent('click',{bubbles:true})));assert.equal(await mentionPopover.getAttribute('aria-hidden'),'true');pass('社群貼文圖片顯示標記好友按鈕與動畫彈窗');
 await context.request.post(BASE+'/api/logout');await context.request.post(BASE+'/api/login',{data:{email:FRIEND_EMAIL,password:'Friend-password-1'}});
 await page.goto(BASE+'/social.html');await page.locator('#mineFeed article.post-card').first().waitFor();await page.locator('#mineFeed .more-btn').first().click();
 assert.equal(await page.locator('#menu-mine-'+post.id+' .menu-item').count(),2);assert.match(await page.locator('#menu-mine-'+post.id).innerText(),/取消被標記/);assert.match(await page.locator('#menu-mine-'+post.id).innerText(),/檢舉/);pass('我的社群顯示被標記貼文且僅提供取消標記與檢舉');
 await page.locator('#menu-mine-'+post.id+' .menu-item').filter({hasText:'檢舉'}).click();
 await page.goto(BASE+'/memories.html');await page.locator('.day-cell img').first().waitFor();await page.locator('.day-cell img').first().click();await page.waitForSelector('#storyOverlay.active');
 await page.locator('#storyMenuButton').waitFor({state:'visible'});await page.click('#storyMenuButton');assert.equal(await page.locator('#storyMenu').getAttribute('aria-hidden'),'false');assert.equal(await page.locator('#storyMenu [role=menuitem]').count(),2);
 await page.locator('#storyMenu [role=menuitem]').filter({hasText:'檢舉'}).click();await page.click('#storyMenuButton');await page.locator('#storyMenu [role=menuitem]').filter({hasText:'取消被標記'}).click();
 await page.waitForFunction(()=>!document.querySelector('#storyOverlay').classList.contains('active'));await page.waitForFunction(()=>document.querySelectorAll('.day-cell img').length===0);pass('被標記貼文進入 Memories，B 可檢舉或取消標記');
 await context.request.post(BASE+'/api/logout');await context.request.post(BASE+'/api/login',{data:{email:EMAIL,password:'Browser-password-1'}});await page.goto(BASE+'/social.html');await page.waitForSelector('#mineFeed article.post-card');
 await page.locator('#mineFeed .more-btn').first().click();await page.locator('.menu-item.delete').first().click();
 await page.waitForFunction(()=>document.querySelectorAll('#mineFeed .post-card').length===0);
 assert.equal((await (await context.request.get(BASE+'/api/get_memories')).json()).length,0);pass('社群刪除整則多圖紀錄');
 await page.goto(BASE+'/home.html');await page.click('.shutter-btn');assert.match(await page.locator('#action-sheet-overlay').getAttribute('class'),/show/);
 const quickResponse=page.waitForResponse(r=>r.url().endsWith('/api/upload_memory_post'));
 await page.setInputFiles('#input_gallery',path.resolve('frontend/IMG_1940.jpg'));
 const quick=await quickResponse;assert.equal(quick.status(),200,await quick.text());
 await page.waitForFunction(()=>document.querySelector('#displayImg').getAttribute('src').startsWith('/api/photos/'));
 assert.ok(page.url().endsWith('/home.html'));pass('快門相簿直接上傳並留在首頁');
 await page.goto(BASE+'/memories.html');await page.locator('.day-cell img').first().click();await page.waitForSelector('#storyOverlay.active');
 await page.click('#storyOverlay .delete-btn');await page.waitForFunction(()=>!document.querySelector('#storyOverlay').classList.contains('active'));
 await page.reload();assert.equal(await page.locator('.day-cell img').count(),0);pass('日曆限動刪除最後一圖，重載無舊照片');
 await page.goto(BASE+'/login.html');await context.request.post(BASE+'/api/logout');await page.goto(BASE+'/forgot-password.html');await page.fill('#emailInput',EMAIL);await page.click('#submitBtn');await page.waitForURL('**/otp_verify.html?**');
 await page.fill('#real-input',otp('reset_password'));await page.click('#verifyBtn');await page.waitForURL('**/reset_password.html?**');
 await page.fill('#newPass','Changed-password-2');await page.fill('#confirmPass','Changed-password-2');await page.click('#submitBtn');await page.waitForURL('**/login.html**');
 await page.fill('#emailInput',EMAIL);await page.fill('#passwordInput','Changed-password-2');await page.click('#loginBtn');await page.waitForURL('**/index.html');pass('忘記密碼 → OTP → 重設 → 新密碼登入');
 assert.deepEqual(errors,[]);pass('瀏覽器無 JavaScript 例外');
 fs.mkdirSync('test-results',{recursive:true});fs.writeFileSync('test-results/features.json',JSON.stringify({checks},null,2));
 }catch(e){console.error('Browser errors:',errors);console.error('Page:',await page.locator('body').innerText());throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
